### ISSUE TITLE
[Safari] "Host An Event" button and "Search By Zip Code" input field should have smaller heights

### ISSUE THREAD

**Issue by cbcowans** [aclu-people-power/map#105]
In Safari, the heights of "Host An Event" and "Search by Zip Code" are slight larger as compared to the date and type event filters.

![screen shot 2017-04-27 at 7 47 13 am](https://cloud.githubusercontent.com/assets/215242/25489172/e02d3054-2b1d-11e7-82f7-daab4e72d0dd.png)

**Comment by stuartsan** [comment]
Closed by #107
