### ISSUE TITLE
Map not loading up on iPhone 5S, iPhone 7 in Safari

### ISSUE THREAD

**Issue by kpenning** [aclu-people-power/map#109]
Getting multiple reports from team members that map view does not work on iPhones 5S and 7 in Safari. Confirmed on BrowserStack that is the case for the iPhone 7. On BrowserStack's iPhone 5S, I get an outdated browser error even if I'm using Chrome.

**Real live iPhone 5S:**
![image](https://cloud.githubusercontent.com/assets/4789544/25732492/320c9242-311e-11e7-89d0-04378ffae7da.png)

**BrowserStack iPhone 7:**
![bs_ios_mobile_iphone 7-10 0](https://cloud.githubusercontent.com/assets/4789544/25732503/4b00daba-311e-11e7-83f0-fe298938ae3d.jpg)

**Comment by stuartsan** [comment]
@kpenning, iOS7 and below does not support webgl, which is required for the mapbox library. The browserstack iphone 5s is on iOS7, so that's what's happening there. For anything newer though, there was a flexbox bug addressed by this PR https://github.com/aclu-people-power/map/pull/111/files
