### ISSUE TITLE
UI: outdated browser message

### ISSUE THREAD

**Issue by stuartsan** [aclu-people-power/map#11]
Should there be any loading / error states defined?

**Comment by ryanhobsonsmith** [comment]
Two states that would be nice to get designs for are:

~~1. Loading bar/message while zip codes, map & events are being downloaded and initialized~~

2. Message to show to user's on outdated browsers that won't support our site.

**Comment by mollieru** [comment]
@ryanhobsonsmith do you know what the text would be for the unsupported browser message? Or can you shoot me an example or two?

**Comment by mollieru** [comment]
Also, how much time is loading taking on avg ?

**Comment by stuartsan** [comment]
@mollieru , here is a pull request that proposes a simple loading screen -- it includes a video of loading on a slow connection: https://github.com/aclu-people-power/map/pull/86

Re: loading time, it is hard to quantify exactly at this moment cause we do not have a dev environment quite like the production environment, but overall the load time will be quite good, IMO.

If that loading screen is cool ~ish we can cross off that ask, LMK what you think.

The unsupported browser message could be changed too, but right now it is something like

>  Sorry, you are using an outdated browser. Please <a href="http://outdatedbrowser.com/en">upgrade to a newer version</a> in order to view this site properly.

**Comment by mollieru** [comment]
Looks great!

**Comment by mollieru** [comment]
Just to follow up, what you've got now looks good to go.

**Comment by stuartsan** [comment]
Thanks @mollieru , I will merge that loading screen PR. The only other piece represented by this issue is the "update your browser" screen; I'm happy to just improvise something for that, I feel like it is a pretty edgy edge case, but let's touch on this when we sync up tomorrow.

**Comment by stuartsan** [comment]
Update: I'll (or someone else who is comfortable with it can) just improvise something here and get feedback. Note, there is an open PR #51 to A) bring up to date w master, and B) update the styling.

**Comment by stuartsan** [comment]
@mollieru , how about something like this, at least as a starting place for the V1?

![image](https://cloud.githubusercontent.com/assets/1724544/25415477/bba4942a-29ec-11e7-8e5d-8ac642799158.png)

The link is going to http://outdatedbrowser.com/en.

cc also @kpenning to see if this copy is 👍 .

**Comment by kpenning** [comment]
Copy is great. Can we just hide the map instead of the entire website?

**Comment by mollieru** [comment]
+1 to @kpenning if possible

**Comment by stuartsan** [comment]
@mollieru / @kpenning  , we can def do something like that but probably out of scope for the V1 because the general layout uses flexbox, and that too may be all borked in unsupported browsers.

I put this in for now, to have _something_:

![image](https://cloud.githubusercontent.com/assets/1724544/25488726/9cde82f4-2b1c-11e7-8499-caa14d19d4ec.png)

If that doesn't work for the V1 LMK and we can update as needed.

**Comment by mollieru** [comment]
Looks great!
