### ISSUE TITLE
Switch default order to closest by distance

### ISSUE THREAD

**Issue by kpenning** [aclu-people-power/map#114]
Based on feedback from numerous volunteers, I think we need to sort by nearest event rather than time.

> hey there!
> i wanted to make sure that for small states like RI, when I enter my zipcode, instead of listing events in distance order from the zipcode, it seems to list them in other ways.
> i think this will make it more difficult for people in the RI region to know where to go. I think you're listing them by date now, which kind of makes sense, but it'd be great if there was a toggle, and (given that the main search criteria is zip code) it defaulted to distance from zipcode.
> thoughts?
> I love the new search options though!
> kate

> Hello! I am an organizer in Berkeley and have been sending people to the PeoplePower.org site to find our local events. Unfortunately the new update you made is a huge downgrade in search functionality. When I punch in a Berkeley zip code, the first 10-15 events that pop up are anywhere from 15-30 minutes away and none of them are in Berkeley—they are all in other cities. This is a big problem because it forces people to click excessively to find an event and we all know that additional clicks are terrible when you are getting someone to buy in to an organization or an event. Can you fix this? I am doing a huge push in outreach that I need to put on hold until you fix the issue. Keep me posted.
> Thanks, Erika

**Comment by stuartsan** [comment]
#115 addresses this by sorting by distance when a zipcode is selected. If we want add an additional control to toggle sort by distance/datetime it'd be helpful to get some design guidance to address both the desktop/mobile cases.
