### ISSUE TITLE
Facebook share link

### ISSUE THREAD

**Issue by stuartsan** [aclu-people-power/map#13]
I don't think these are in the designs, but they're in the spec document, which specifies a facebook sharing link...where should this be visually?

**Comment by stuartsan** [comment]
Also -- would be cool to avoid loading third party garbage JS if we can, e.g., for a share button. This would lessen the amount of stuff the user has to download, and would be better for privacy.

Also also -- might need to do og tags etc so it looks decent when shared.

**Comment by stuartsan** [comment]
See updated designs for facebook share button. No third party JS needed, just do a link kinda like:

```
href="https://www.facebook.com/sharer/sharer.php?u=${location.href}
```
Note: test out sharing it, add og tags etc as needed so that it looks legit when shared.

![image](https://cloud.githubusercontent.com/assets/1724544/24830219/2a642e62-1c36-11e7-86a6-1db77e97b1be.png)

![image](https://cloud.githubusercontent.com/assets/1724544/24830222/2f5a5680-1c36-11e7-84a8-3b280811c30d.png)

**Comment by stuartsan** [comment]
See https://github.com/aclu-people-power/map/issues/84#issuecomment-292790509 -- also one other thing here, for the desktop design there will always be an event list sidebar on the right. How does that change where this button should go?

**Comment by mollieru** [comment]
@kpenning what's driving the request for this feature? Why Facebook and not other social sharing platforms? Have you seen successful adoption/click through when share buttons are used? 

I'm curious to understand if there's meaningful sharing that happens as a result of this --or if there's a way to include a share ask elsewhere on the peoplepower.org (and on blog posts/map-related calls to action on the main ACLU site).

**Comment by mollieru** [comment]
@hgsigala do you have insight to the above Qs?

**Comment by stuartsan** [comment]
> also one other thing here, for the desktop design there will always be an event list sidebar on the right. How does that change where this button should go?

Move that button to the left hand side

@mollieru is looking into reworking for more vertical space.

**Comment by mollieru** [comment]
@stuartsan  issue https://github.com/aclu-people-power/map/issues/89 resolves this for mobile and here's an updated design to illustrate the desktop view: 

![screen shot 2017-04-24 at 12 12 34 pm](https://cloud.githubusercontent.com/assets/3680494/25346971/5f201b62-28e7-11e7-85af-f626e7bcf568.png)

**Comment by stuartsan** [comment]
Breaking up the work a little differently to group together mobile/desktop related tasks -- now represented by #91/#92.
