### ISSUE TITLE
Optimize for production

### ISSUE THREAD

**Issue by stuartsan** [aclu-people-power/map#27]
Make sure we're doing all we can to optimize delivery of assets.

- Probably use Cloudfront vs raw s3 (right now events data is coming directly from s3, I think)
- HTTP/2 enabled in Cloudfront distribution
- Asset hashing (to better break caches)
- Determine how / if bundle.js should be split for best performance
- Make sure [things are gzipped](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html)

Audit in devtools network tab for any other red flags.

**Comment by ryanhobsonsmith** [comment]
Asset hashing looks like it's working correctly. No compelling reason to split bundle.js up yet that I can think of, can revisit once we see what final build size looks like.
 
Rest of this is blocked until we have AWS credentials to verify cloudfront setup.

**Comment by stuartsan** [comment]
Also, for reference, I ran WPT against this in dev, it provides a nice checklist of issues: https://www.webpagetest.org/result/170402_EJ_9HK/

Also just for fun, here is a reference point of WPT run against the existing map site, https://www.webpagetest.org/result/170402_2V_9JM/

**Comment by stuartsan** [comment]
This stuff is all looking pretty good for now! Closing.
