### ISSUE TITLE
Optimize initial page load visually

### ISSUE THREAD

**Issue by stuartsan** [aclu-people-power/map#48]
Prevent flashes of unstyled content and template content like `{{ hihi }}`, test w/ dev tools timeline with screenshots and ensure that the initial loading experience looks good and feels fast. Clear cache / open new incognito window between reloads :grin:

**Comment by stuartsan** [comment]
Note: gotta test against the production build, cause the initial page load is different vs when using webpack dev server with hot reloading.

**Comment by ryanhobsonsmith** [comment]
Think I've cleaned up all we can until UI gets further along (or we have better defined loading screen designs).

**Comment by stuartsan** [comment]
This is in a pretty good place from #86 -- closing.
