### ISSUE TITLE
Browserstack testing account

### ISSUE THREAD

**Issue by stuartsan** [aclu-people-power/map#54]
[Browserstack](https://www.browserstack.com/pricing) is a great tool for cross browser testing and they have free accounts for open source projects. Can we contact them to see if we can get one?

**Comment by cbcowans** [comment]
This is in progress. Their head of sales is working out what they can give us.

**Comment by stuartsan** [comment]
👍 , thx @cbcowans

**Comment by kpenning** [comment]
Stuart, PM me if you still want BrowserStack. I have an account for our consulting firm and you can use it.

**Comment by stuartsan** [comment]
We got a browserstack account, closing!
