### ISSUE TITLE
Map requirements doc vs design discrepancies

### ISSUE THREAD

**Issue by stuartsan** [aclu-people-power/map#61]
Any action we need to take for the following items in the map requirements doc that don't appear to be represented in the designs?

UPDATED:

- Prominent link to share the map on Facebook (see #13 )
- ~~All aclu.org email addresses go into the flow as official events (I don't know what this means, does the map need to do anything or is this on the AK side?)~~
- ~~Sort events by distance and time (would be great if this could be omitted)~~
- ~~Shows distance to event from zip code~~ design not needed, we can copy something like what the old map is doing
- Link to privacy policy (also where is the privacy policy?)

**Comment by kpenning** [comment]
- We do need to add a link to share on FB. Can Mollie figure out a place for that, maybe?
- ACLU.org email addresses thing ignore
- We definitely need to be able to sort the events list by time. How is it setup right now?
- Distance to event should be doable, no? We have it on our current map.
- Privacy policy here: https://go.peoplepower.org/signup/privacy/

**Comment by stuartsan** [comment]
> We definitely need to be able to sort the events list by time. How is it setup right now?

Right now Ethan is modifying the feed so that all events are pre-sorted by datetime, in order of soonest to most distant. Should the UI support reversing that? I'm not sure what the use case is where that'd be useful, but if it is important, we can definitely add it, just need designs for what it should look like.

> Distance to event should be doable, no? We have it on our current map.

Yep calculating from the zip code center is no big deal, just need design guidance on where to display

**Comment by stuartsan** [comment]
...and I feel like if we're sorting by time already _and_ showing distance to a given zip code for each event, plus there is usually a map in sight, might be able to get away with not needing to toggle between "sort by date/sort by distance".

**Comment by kpenning** [comment]
Ah yes we can get rid of that datetime sorter. There's never a need to go the other way. Sorry was confused.

In the list, we can put a small (8mi away) in parentheses next to each event or something. Similar to the current map is fine.

**Comment by stuartsan** [comment]
Updated the original comment to reflect those that still need design input. Thanks @kpenning !
