### ISSUE TITLE
UX: search button

### ISSUE THREAD

**Issue by stuartsan** [aclu-people-power/map#68]
Because of the fact that we have basically all the data available on the client after the initial app boot, i.e., we are not making any additional network requests when the user interacts with the UI, right now the filters (event date/type, zipcode) are wired up to immediately update the events display (both map and list) when the user interacts with them (for zipcodes, it's only updated when it is a 5 digit number, a potentially valid zipcode).

So, the search button isn't really doing anything besides hanging out and looking red. There is one exception, in the mobile filters screen -- but even then, clicking the button is simply closing the filters screen, the search has already happened. For the other two search button instances (mobile + desktop), clicking it does nothing.

My question is: can we remove the search button, at least for the desktop layout?

Alternatively, we could defer the actual event filtering until someone clicks the button, but I feel like faster feedback is probably better, and it feels like rewiring it that way would be forcing the search button paradigm onto an interaction that doesn't need it for any underlying technical reason and might have better options available.

Any thoughts?

**Comment by stuartsan** [comment]
Also: we might need a social sharing link/button, maybe these items are related #13

**Comment by mollieru** [comment]
I think it's fine for us to remove the 'search' button on desktop. Agreed that it's faster/easier to save the user the click.

**Comment by stuartsan** [comment]
Re-opening, gotta re-PR this and fix some styling conflicts
