### ISSUE TITLE
Link to privacy policy

### ISSUE THREAD

**Issue by stuartsan** [aclu-people-power/map#79]
Link href: https://go.peoplepower.org/signup/privacy/

**Comment by stuartsan** [comment]
See updated design -- also add the ACLU 2017 copyright

![image](https://cloud.githubusercontent.com/assets/1724544/24830165/65e6f754-1c35-11e7-9722-5ea1a2c61606.png)

![image](https://cloud.githubusercontent.com/assets/1724544/24830171/724bcfb0-1c35-11e7-873f-4f45169e3745.png)

**Comment by stuartsan** [comment]
See https://github.com/aclu-people-power/map/issues/84#issuecomment-292790509

**Comment by mollieru** [comment]
lgtm!

**Comment by mollieru** [comment]
Updated design in issue https://github.com/aclu-people-power/map/issues/13 resolves this for desktop and https://github.com/aclu-people-power/map/issues/89 for mobile.

**Comment by stuartsan** [comment]
Closing in favor of #91/#92 which represent the same work grouped differently.
