### ISSUE TITLE
Add "host an event" button for mobile

### ISSUE THREAD

**Issue by stuartsan** [aclu-people-power/map#84]
Updated design:

![image](https://cloud.githubusercontent.com/assets/1724544/24830623/ca56d25a-1c3e-11e7-8b8e-6b7f2c19eefb.png)

**Comment by stuartsan** [comment]
Hmm, looking more closely at this, I think we have a height availability problem going on in the mobile design, particularly with the newest updates. For example, on an iphone 5 (320x568), just by adding an additional button like this and before adding the new footer with the privacy policy / share button, it looks like this:

![image](https://cloud.githubusercontent.com/assets/1724544/24838129/a9c7930e-1cf6-11e7-913e-9596810c8598.png)

That is also without the user's browser chrome.

I am imagining that the mobile layout is fixed, i.e., the header and footer do not move, but you can interact with the event list or the map in the middle by scrolling or zooming, respectively. Is this correct? To me that would make sense for this type of layout, particularly because of the map's role in it (e.g., scrolling _past_ the map in this context to get to the footer seems off, IMO).

If that is correct, the height of the header and footer are leaving a practically unusably-sized map or event list in between them for commonly sized mobile devices.

A couple thoughts:

- The search button doesn't really do anything, it could be dispensed with as in the desktop layout
- I feel like toggling "map/list" view as well as "flitering" are common paradigms that are easily understood by being represented solely as an icon
- If the header/footer should always be in view, we'll need to also find a way to minimize the footer height -- as shown in the design it is taking up a lot of precious real estate

Any thoughts on how to proceed? I'm going to mark this and the other related ones as blocked so we don't duplicate too much effort here.

**Comment by kpenning** [comment]
Thanks for this, Stuart. Here are my thoughts:

1) Let's convert the default view on mobile to list mode. Maps will largely be useless on a phone (at least they are if you try them on map.peoplepower.org right now) because they're so jittery.

2) Then we could have Mollie design a map icon that is smaller as well as a filter icon. The host an event link can be the phrase still.

3) I'm partial to keeping the search button for old people. 

4) The header logo does not need to always be in view imo. I don't mind allowing users to scroll past it.

**Comment by mollieru** [comment]
Hi, a few thoughts:

1. Agreed w @kpenning's plan above

2. Given the age and tech familiarity of our users, I wouldn't assume that icons will mean much -- I can try to come up with other ways to save vertical space

3. @kpenning is it ok w you if the footer appears at the bottom of the list view but not on the map view? 

Check out how Our Revolution treats it for reference: http://map.ourrevolution.com/?source=ws170411-smaller-module

**Comment by mollieru** [comment]
@hgsigala any thoughts on the above?

**Comment by stuartsan** [comment]
@mollieru is working on reconfiguring this vertical space situation.

**Comment by stuartsan** [comment]
Closing in favor of #91/#92 which represent the same work grouped differently.
