### ISSUE TITLE
Map: remove clusters

### ISSUE THREAD

**Issue by stuartsan** [aclu-people-power/map#87]
The present implementation of the map, following the design, clusters events together when zoomed out, and after zooming in to a certain level, shows individual event markers:

![image](https://cloud.githubusercontent.com/assets/1724544/24975477/a612d242-1f7a-11e7-8207-d0bdf53d20c3.png)

@kpenning mentioned that people power stakeholders have expressed a desire to _not_ cluster events on the map, and instead always show individual markers, so that users experience a sense of there being a large number of events.

This is doable but requires design reworking so that the individual markers do not overlap (i.e. they need to be smaller, probably circular?) and a new style for aclu official events.

Some unsolicited thoughts on the topic:

- I totally understand the desire to express to users the large number of events, but I do not feel confident that many dots will better impress upon users a sense of many events, compared to clusters. It feels like an overly literal assumption. Do we have any user research or a/b testing that confirms the hypothesis? (If not could we?)

- My view is that clustering is more usable in some ways -- without clustering, accurately clicking a particular, small, event marker while zoomed out can be very difficult, even impossible depending on the density. With clusters, there is another mechanism for navigating the map: you can click clusters and progressively zoom into a particular area.

- We could also keep clusters but tweak the cluster radius so that there are more total markers (both clusters and individual markers) shown on the map at any given zoom level.

Ultimately I am up for implementing whatever the folks who we are building this for want, but I wanted to express my POV on it and see what people think. To update the design, on the dev side we will just need a new mockup. Let me know if any thoughts.

**Comment by stuartsan** [comment]
cc @mollieru @hgsigala

**Comment by stuartsan** [comment]
I am going to tweak the map around a bit like this:

- Drops clusters, individual circle markers instead
- No visual distinction for official events on map, but stars in events list

And post screenshots in here for design feedback.

**Comment by stuartsan** [comment]
@mollieru, here are simple circles at 6px. I feel like this is a decent balance of "show a lot of dots but have it not be extremely hard to click on an individual dot".

![image](https://cloud.githubusercontent.com/assets/1724544/25354347/83dac0f6-28e7-11e7-813a-dea6799c91f7.png)

![image](https://cloud.githubusercontent.com/assets/1724544/25354369/99249752-28e7-11e7-9aad-af2d1ff111f6.png)

One pixel here makes a pretty big difference -- here is 7px:

![image](https://cloud.githubusercontent.com/assets/1724544/25354561/33d3d59c-28e8-11e7-8fbf-b0e864aa9dde.png)


And 5px:

![image](https://cloud.githubusercontent.com/assets/1724544/25354522/153c8264-28e8-11e7-806c-c5c889ee65a8.png)

---------------------------------

LMK what you think.

**Comment by mollieru** [comment]
Cool! Lookin good. Would you mind plopping in screenshots of 6px and 7px for mobile?

**Comment by stuartsan** [comment]
No problem, here are all three:

5px:
![image](https://cloud.githubusercontent.com/assets/1724544/25363844/b80a74d6-2912-11e7-8142-06f3e8dc4a77.png)

6px:
![image](https://cloud.githubusercontent.com/assets/1724544/25363832/a4853842-2912-11e7-86ed-741dcbc2e534.png)

7px:
![image](https://cloud.githubusercontent.com/assets/1724544/25363869/d3d3839c-2912-11e7-884b-8c5b963a2fd3.png)

**Comment by mollieru** [comment]
Ok thanks! Let's go w 6px.

**Comment by stuartsan** [comment]
Ok sweet, will do, thanks!
