### ISSUE TITLE
Revise mobile layout to enhance vertical space

### ISSUE THREAD

**Issue by mollieru** [aclu-people-power/map#89]
@stuartsan here's a revised design which addresses https://github.com/aclu-people-power/map/issues/84 https://github.com/aclu-people-power/map/issues/79 and https://github.com/aclu-people-power/map/issues/13:

![screen shot 2017-04-24 at 12 08 58 pm](https://cloud.githubusercontent.com/assets/3680494/25346845/dbe8410c-28e6-11e7-9fbe-eb07f277de7e.png)
![screen shot 2017-04-24 at 12 08 31 pm](https://cloud.githubusercontent.com/assets/3680494/25346828/c4699d82-28e6-11e7-82e8-82cdef3fe181.png)

**Comment by stuartsan** [comment]
Excellent, thank you @mollieru

**Comment by stuartsan** [comment]
Closing this in favor of the issues that represent the tasks here (#91, #93). Thanks @mollieru !
