### ISSUE TITLE
Desktop: add external links

### ISSUE THREAD

**Issue by stuartsan** [aclu-people-power/map#92]
For the desktop view we need to add links to:

- [x] share on facebook
    - `https://www.facebook.com/sharer/sharer.php?u=${location.href}`
- [x] privacy policy
  - https://go.peoplepower.org/signup/privacy/

Design:

![image](https://cloud.githubusercontent.com/assets/1724544/25365164/d637fd1c-291b-11e7-93ed-2d7589718410.png)

**Comment by tasandberg** [comment]
I'm going to handle this as part of the same work as #91, since we should probably use the same elements which style changes in the media query.
